### PR TITLE
fixes webpacker:clean erroring because of nested hashes on manifest

### LINKED ISSUE #2310: TypeError: no implicit conversion of Hash into String (Assets clean)
Getting the following error on heroku when using assets:clear (on master)

```rb
 TypeError: no implicit conversion of Hash into String
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `join'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `block in clean'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `map'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `clean'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker.rb:27:in `clean'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/tasks/webpacker/clean.rake:6:in `block (2 levels) in <main>'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/tasks/webpacker/clean.rake:13:in `block in <main>'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
````

related #1410

### PR DESCRIPTION
**Pull request by LuanGB**
Fixes #2310

### CODE REVIEW

**Comment by LuanGB** [comment]
@jakeNiemiec I believe these changes are a bit more idiomatic than the previous added pr, plus it includes at least one test to ensure it won't happen again.

**Comment by swrobel** [comment]
FYI, this should be merged before a new release is cut, as Heroku is waiting on this being functional & stable to add webpacker caching support, which would really speed up build times: https://github.com/heroku/heroku-buildpack-ruby/pull/892

File: lib/webpacker/commands.rb [hunk 1]
```diff
@@ -7,10 +7,11 @@ def initialize(webpacker)
 
   def clean(count_to_keep = 2)
     if config.public_output_path.exist? && config.public_manifest_path.exist?
-      files_in_manifest = manifest.refresh.values.map { |f| File.join config.root_path, "public", f }
-      files_to_be_removed = files_in_manifest.flat_map do |file_in_manifest|
+      files_in_manifest = process_manifest_hash(manifest.refresh)
+      files_to_be_removed = files_in_manifest.map do |file_in_manifest|
         file_prefix, file_ext = file_in_manifest.scan(/(.*)[0-9a-f]{20}(.*)/).first
         versions_of_file = Dir.glob("#{file_prefix}*#{file_ext}").grep(/#{file_prefix}[0-9a-f]{20}#{file_ext}/)
+        next "" unless versions_of_file.any?
```
Comment (swrobel) [inline lib/webpacker/commands.rb]:
```suggestion
        next unless versions_of_file.any?
```
I'm not sure why it's preferable to insert `""` instead of `nil`

File: lib/webpacker/commands.rb [hunk 2]
```diff
@@ -7,10 +7,11 @@ def initialize(webpacker)
 
   def clean(count_to_keep = 2)
     if config.public_output_path.exist? && config.public_manifest_path.exist?
-      files_in_manifest = manifest.refresh.values.map { |f| File.join config.root_path, "public", f }
-      files_to_be_removed = files_in_manifest.flat_map do |file_in_manifest|
+      files_in_manifest = process_manifest_hash(manifest.refresh)
+      files_to_be_removed = files_in_manifest.map do |file_in_manifest|
```
Comment (swrobel) [inline lib/webpacker/commands.rb]: Why the switch from `flat_map` to `map`? I now see this inserting `[]` elements into `files_to_be_removed` which will throw `TypeError: no implicit conversion of Array into String` which is different but no improvement from the previous error about hashes.

File: lib/webpacker/commands.rb (hunk 1 above)
Comment (swrobel) [reply lib/webpacker/commands.rb]: Actually, on second thought, I think it's better to just remove this line. You end up with an array like `[nil, nil, nil]` if there are no versions of 3 files instead of `[]` with the previous code. Your version will require the last line of this method to be changed to `files_to_be_removed.compact.each { |f| File.delete f }` (added `.compact`) in order to avoid `TypeError: no implicit conversion of nil into String`

**Comment by gauravtiwari** [comment]
Hi @LuanGB Thanks for the fix. @swrobel thanks for reviewing.  

Could you please review and address the comments? Happy to merge this in once the comments are resolved.

**Comment by LuanGB** [comment]
@gauravtiwari and @swrobel I'll probably be looking into this today to fix the underlined issues

**Comment by LuanGB** [comment]
@jakeNiemiec @gauravtiwari and @swrobel I think it's good to go now!

**Comment by swrobel** [comment]
lgtm

**Comment by saiqulhaq** [comment]
please merge

**Comment by kikonen** [comment]
I think I hit this issue also (as part of my first experiment with this webpacker gem...). 

Any ETA when release including fix would be available?
